# version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.developer.txt
    container_name: api-hamsterthief
    ports:
      - "5003:5003"
    expose:
      - "5003"
    networks:
      - hamsterthief_net
    depends_on:
      - mysql
      - redis
      
  mysql:
    image: mysql:8.0.27
    container_name: hamsterthiefmysql
    restart: always
    environment: 
      MYSQL_DATABASE: hamsterthief    
      # MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - hamsterthief_net

  redis:
    image: redis:alpine
    container_name: hamsterthiefredis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hamsterthief_net

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: overcodeport
  #   run: npm run build
  #   networks:
  #     - hamsterthief_net

  # nginx:
  #   build:
  #     context: /nginx
  #     dockerfile: Dockerfile.nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #     # - frontend
  #   networks:
  #     - hamsterthief_net
volumes:
  mysql_data:
  redis_data:
networks:
  hamsterthief_net:

